# Generated by Django 5.2.1 on 2025-05-14 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magento', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyorderdetail',
            name='buy_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='buy_order_detail', to='magento.buyorder'),
        ),
        migrations.AlterField(
            model_name='buyorderdetail',
            name='email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='buy_order_detail', to='magento.customer'),
        ),
    ]
