# Generated by Django 5.2.1 on 2025-05-15 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magento', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyorderdetail',
            name='buy_order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='buy_order_detail', to='magento.buyorder'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
