# Generated by Django 5.2.1 on 2025-05-16 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('magento', '0002_alter_buyorderdetail_buy_order_alter_customer_phone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='buyorderdetail',
            options={'ordering': ['-buy_order_external_id'], 'verbose_name': 'Detalhes da Ordem de Compra', 'verbose_name_plural': 'Detalhes das Ordens de Compra'},
        ),
    ]
