# Generated by Django 5.2 on 2025-05-07 04:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BuyOrder',
            fields=[
                ('buy_order', models.IntegerField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Ordem de Compra',
                'verbose_name_plural': 'Ordens de Compra',
                'ordering': ['-buy_order'],
                'indexes': [models.Index(fields=['buy_order'], name='mgt_buyorde_buy_ord_d7d344_idx')],
            },
        ),
        migrations.CreateModel(
            name='MgtCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_external_id', models.IntegerField(blank=True, null=True, unique=True)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('cpf', models.CharField(max_length=11, unique=True)),
                ('phone', models.CharField(max_length=20)),
                ('customer_group', models.CharField(blank=True, max_length=255, null=True)),
                ('customer_since', models.DateTimeField(blank=True, null=True)),
                ('last_purchase', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'indexes': [models.Index(fields=['email'], name='mgt_mgtcust_email_e0ba72_idx'), models.Index(fields=['cpf'], name='mgt_mgtcust_cpf_8cb385_idx'), models.Index(fields=['cpf', 'email'], name='mgt_mgtcust_cpf_4e920b_idx')],
            },
        ),
        migrations.CreateModel(
            name='BuyOrderDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buy_order_external_id', models.IntegerField(unique=True)),
                ('purchase_date', models.DateTimeField()),
                ('status', models.CharField(max_length=255)),
                ('payment_type', models.CharField(max_length=255)),
                ('shipping_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('buy_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='buy_order_details', to='mgt.buyorder')),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='buy_order_details', to='mgt.mgtcustomer')),
            ],
            options={
                'verbose_name': 'Detalhes da Ordem de Compra',
                'verbose_name_plural': 'Detalhes das Ordens de Compra',
                'ordering': ['-purchase_date'],
                'indexes': [models.Index(fields=['email'], name='buyorderdetail_email_idx'), models.Index(fields=['buy_order'], name='buyorderdetail_buy_order_idx')],
            },
        ),
    ]
